name: ballerina tests
on: [push]
jobs: 
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - uses: ballerina-platform/setup-ballerina@v1
          name: Install Ballerina
          with:
            version: 2201.5.0
        - run: bal version
        - run: bal test
