name: ballerina tests
on: [push]
jobs: 
  test:
    runs-on: 
      - macos-latest
      - ubuntu-latest
      - windows-latest
    steps:
        - uses: actions/checkout@v3
        - uses: ballerina-platform/setup-ballerina@v1
          name: Install Ballerina
          with:
            version: 2201.5.0
        - run: bal version
        - run: bal test
